#!/bin/bash

### A linux learn container environment configuration.
### Author by Airdb Team @ 2015 - Now
export VISIBLE=now
export DEBIAN_FRONTEND=noninteractive
export PS1='\033[32m[\u@\H \W]\033[0m\\$ '

TMOUT=300
